stages:
  preprocess:
    cmd: python src/split_data.py && python src/normalize_data.py
    deps:
      - src/split_data.py
      - src/normalize_data.py
      - data/raw/raw.csv
    outs:
      - data/processed/X_train_scaled.csv
      - data/processed/X_test_scaled.csv
  train:
    cmd: python src/grid_search.py && python src/train_model.py
    deps:
      - src/grid_search.py
      - src/train_model.py
      - data/processed/X_train_scaled.csv
      - data/processed/X_test_scaled.csv
    outs:
      - models/model.pkl
  evaluate:
    cmd: python src/evaluate.py
    deps:
      - src/evaluate.py
      - models/model.pkl
    metrics:
      - metrics/scores.json
